#pragma once
#define ANIMATION_TOLERANCE             0.01f
#define ANIMATION_DURATION              0.5f
#define ANIMATION_SIZEUP_DURATION       0.1f
#define ANIMATION_ICON_SIZEUP_SCALE     0.1f
#define ANIMATION_POPUP_DURATION        0.15f
#define UIOBJECT_ICON_MARGIN            0.005f
#define UIOBJECT_OUTLINE_DARKENING      0.7f
#define UIOBJECT_OUTLINE_SCALE          0.0025f
#define FRONTPANEL_BORDER_SIZE_SCALE    0.005f
#define FRONTPANEL_SIZEUP_DURATION      1.2f
#define MINIMENU_MARGIN_SCALE           0.01f
#define SLIDER_LINEWIDTH_SCALE          0.005f
#define SLIDER_GRABPOINT_SCALE          0.01f